"use client";

import React, {
  createContext,
  useContext,
  useEffect,
  useMemo,
  useState,
} from "react";

type Locale = "en" | "ar";
type Theme = "light" | "dark";

interface AppPreferencesValue {
  locale: Locale;
  theme: Theme;
  isArabic: boolean;
  setLocale: (locale: Locale) => void;
  toggleLocale: () => void;
  toggleTheme: () => void;
  t: (key: string) => string;
}

const translations: Record<Locale, Record<string, string>> = {
  en: {
    signIn: "Sign In",
    register: "Create account",
    getStarted: "Get started",
    signOut: "Sign out",
    dashboard: "Dashboard",
    courses: "Courses",
    organizations: "Organizations",
    language: "العربية",
    lightMode: "Switch to light mode",
    darkMode: "Switch to dark mode",
    chooseOrganization: "Choose your organization",
    organizationHint: "Select the learning community you belong to.",
    noOrganizations: "No active organizations are available right now.",
    loadOrganizationsError:
      "We could not load organizations. Please try again.",
    loadingOrganizations: "Loading organizations...",
    registrationTitle: "Join EduSphere Today",
    registrationSubtitle: "Create your student profile and start learning",
    fullName: "Full Name",
    emailAddress: "Email Address",
    password: "Password",
    personalPhone: "Personal Phone Number",
    educationLevel: "Education Level",
    gender: "Gender",
    male: "Male",
    female: "Female",
    school: "School / University",
    address: "Address / City",
    parentName: "Parent / Guardian Name",
    parentPhone: "Parent Phone Number",
    createStudentAccount: "Create Student Account",
    alreadyRegistered: "Already registered?",
    signInHere: "Sign in here",
    passwordHint: "Must include Upper, Lower, Number & Symbol (e.g. Pass@123)",
    registrationSuccess: "Registration Successful!",
    verifyInstruction:
      "Please check your email to verify and activate your account.",
    registrationFailed: "Registration Failed",
    registrationError: "Could not register account",
    loginSubtitle: "Enter your credentials to access your dashboard",
    rememberMe: "Remember me",
    forgotPassword: "Forgot password?",
    noAccount: "Don't have an account?",
    createAccount: "Create an account",
    primary: "Primary",
    preparatory: "Preparatory",
    secondary: "Secondary",
    university: "University",
    graduate: "Graduate",
    other: "Other",
    welcomeBack: "Welcome Back!",
    signedInMessage: "Successfully signed into your account.",
    authenticationFailed: "Authentication Failed",
    invalidCredentials: "Invalid credentials",
    verifyAlmostThere: "Almost There",
    verifyEmailTitle: "Verify Your Email Address",
    verifyEmailMessage: "We have sent a verification link to",
    yourEmailAddress: "your email address",
    verifyEmailActivate: "Please check your inbox to activate your account.",
    linkValidFor: "The verification link is valid for",
    minutes: "minutes",
    checkSpam: "If you do not see the email, check your Spam or Junk folder.",
    openEmailProvider: "Open Email Provider",
    openGmail: "Open Gmail",
    openOutlook: "Open Outlook",
    backToSignIn: "Back to Sign In",
    wrongEmail: "Wrong email address?",
    registerAnotherEmail: "Register with another email",
    noVerificationToken: "No verification token found in URL.",
    emailVerified: "Email Verified!",
    emailVerifiedMessage: "Your email has been successfully verified.",
    verificationFailed:
      "Email verification failed. The link might be invalid or expired.",
    verifyingEmail: "Verifying Your Email",
    validatingLink: "Please wait while we validate your activation link...",
    accountActivated: "Account Activated",
    verifiedSuccessfully: "Email Verified Successfully!",
    accountActiveMessage:
      "Your email address has been confirmed and your student account is now fully active.",
    redirectingLogin: "Redirecting to login in",
    verificationFailedTitle: "Verification Failed",
    linksExpire:
      "Verification links expire after 15 minutes. If your link has expired, log in or register again to get a new one.",
    retry: "Retry",
    forgotTitle: "Forgot your password?",
    forgotSubtitle:
      "Enter your email and we will send you a secure reset link.",
    sendResetLink: "Send reset link",
    resetEmailSent: "Reset link sent",
    resetEmailSentMessage:
      "If an account exists for this email, you will receive password reset instructions shortly.",
    resetTitle: "Create a new password",
    resetSubtitle: "Choose a strong password for your EduSphere account.",
    newPassword: "New password",
    confirmPassword: "Confirm password",
    resetPassword: "Reset password",
    passwordMismatch: "Passwords do not match.",
    missingResetToken: "This password reset link is missing its token.",
    resetSuccess: "Password reset successfully",
    resetSuccessMessage: "Your password has been changed. You can now sign in.",
    searchPlaceholder: "Search courses, skills, topics...",
    closeMenu: "Close menu",
    openMenu: "Open menu",
    notifications: "Notifications",
    user: "User",
    myProfile: "My Profile",
    menuNavigation: "Menu Navigation",
    myOverview: "My Overview",
    browseCatalog: "Browse Catalog",
    accountProfile: "Account Profile",
    teachingHub: "Teaching Hub",
    newCourse: "New Course",
    submissionsGrading: "Submissions & Grading",
    profile: "Profile",
    executiveAnalytics: "Executive Analytics",
    usersRoles: "Users & Roles",
    teacherRoster: "Teacher Roster",
    categories: "Categories",
    financialLedger: "Financial Ledger",
    eduSphereLms: "EduSphere LMS",
    platformVersion: "Production-Ready Course Platform v1.0",
    myProfileDescription: "Manage your profile and account settings.",
    exploreCourses: "Explore Courses",
    platformRoles: "Platform & Roles",
    connectSocial: "Connect & Social",
    webDevelopment: "Web Development",
    dataScience: "Data Science & AI",
    businessFinance: "Business & Finance",
    designUx: "Design & UX",
    instructorPortal: "Instructor Portal",
    studentEnrollment: "Student Enrollment",
    adminDashboard: "Admin Dashboard",
    allRightsReserved: "All rights reserved.",
    builtForEducation: "Built for next-generation digital education.",
    privacyPolicy: "Privacy Policy",
    termsService: "Terms of Service",
    security: "Security",
    portal: "Portal",
    closeSidebar: "Close sidebar",
    platformDescription:
      "An enterprise-grade LMS platform for modern digital learning.",
    institutionalDirectory: "Institutional Directory",
    partnerOrganizations: "Partner Organizations & Centers",
    exploreOrganizations:
      "Explore universities, academies, and training centers hosting courses on EduSphere.",
    joinWithCode: "Join with Code",
    organizationJoinCode: "Have an Organization Join Code?",
    joinCodeHint:
      "Enter your academy or school invitation code to link your account, access private lessons, and join classroom schedules.",
    enterJoinCode: "Enter Join Code",
    noOrganizationsListed:
      "No active partner organizations listed at the moment.",
    activeHub: "Active Hub",
    verifiedPartner: "Verified Partner",
    knowledgeBase: "Knowledge Base",
    courseCatalog: "Course Catalog",
    discoverCourses:
      "Discover industry-vetted courses taught by verified instructors across technology, business, and science.",
    searchCourseTopic: "Search course title or topic...",
    allCourses: "All Courses",
    noCoursesMatch: "No courses match your criteria",
    adjustSearch:
      "Try adjusting your search query or selecting a different category filter.",
    general: "General",
    instructor: "Instructor",
    progress: "Progress",
    courseFee: "Course Fee",
    free: "Free",
    viewDetails: "View Details",
    courseTuition: "Course Tuition",
    lifetimeAccess: "Full lifetime access",
    quizAssignmentReview: "Quizzes & coding assignment review",
    completionCertificate: "Certificate of completion",
    enrollCourse: "Enroll in Course",
    courseCurriculum: "Course Curriculum",
    publishingLessons:
      "Lessons are currently being published for this course curriculum.",
    videoLecture: "Video Lecture",
    readingModule: "Reading Module",
    startLesson: "Start Lesson",
    lesson: "Lesson",
    interactiveAssessment: "Interactive Assessment",
    questionOf: "Question {current} of {total}",
    loadingQuestions: "Loading assessment questions...",
    noQuestions: "No questions available",
    noPublishedQuestions:
      "This quiz does not have any published questions yet. Please check back later.",
    typeResponse: "Type your response here...",
    previous: "Previous",
    nextQuestion: "Next Question",
    submitAssessment: "Submit Assessment",
    assessmentPassed: "Assessment Passed!",
    quizSubmitted: "Quiz Submitted",
    yourScore: "Your score",
    points: "points",
    submissionError: "Submission Error",
    failedSubmitQuiz: "Failed to submit quiz. Please try again.",
    quizCompleted: "Quiz Completed!",
    finalScore: "Your final score",
    passedAssessment: "Passed Assessment",
    needsReview: "Needs Review",
    tryAgain: "Try Again",
    worth: "Worth",
    assignmentInstructions: "Assignment Instructions",
    totalPoints: "Total Points",
    missingContent: "Missing Content",
    provideSubmission: "Please provide submission text or a file link.",
    assignmentSubmitted: "Assignment Submitted",
    submissionReceived: "Your submission has been received by your instructor.",
    currentSubmissionStatus: "Current Submission Status",
    grade: "Grade",
    instructorFeedback: "Instructor Feedback",
    yourAnswerNotes: "Your Answer / Notes",
    writeSolution:
      "Write your assignment solution, summary, or response here...",
    projectLink: "Document / Project Link (Optional)",
    cancel: "Cancel",
    submitAssignment: "Submit Assignment",
    externalLearningMaterial: "External Learning Material & Resource",
    supplementaryMaterial:
      "This lesson includes supplementary documentation, project repositories, or interactive study guides.",
    openResource: "Open Resource Link",
    interactiveReading: "Interactive Reading Module",
    studyNotes:
      "Study the notes below and complete the module quizzes & assignments.",
    lessonQuizzes: "Lesson Quizzes",
    noQuizzes: "No quizzes attached to this lesson.",
    questions: "Questions",
    pass: "Pass",
    passed: "Passed",
    failed: "Failed",
    score: "Score",
    retakeQuiz: "Retake Quiz",
    takeQuiz: "Take Quiz",
    lessonAssignments: "Lesson Assignments",
    noAssignments: "No assignments attached to this lesson.",
    graded: "Graded",
    submittedPending: "Submitted (Pending Review)",
    notSubmitted: "Not Submitted",
    viewUpdateSubmission: "View / Update Submission",
    submitWork: "Submit Work",
    instructorFeedbackLabel: "Instructor Feedback",
    noLessonNotes: "No text notes provided for this lesson module.",
    backToLessonNotes: "Back to Lesson Notes",
    courseAccessDenied: "Course access denied",
    courseAccessDeniedHint:
      "This course belongs to another instructor or is no longer available in your teaching workspace.",
    backToTeacherDashboard: "Back to Teacher Dashboard",
    studentProgressSummary:
      "Track course progress, study materials, grades, and academy certifications.",
    affiliation: "Affiliation",
    change: "Change",
    switchOrganizationTitle: "Switch or enter a new organization code",
    joinOrganizationCode: "Join Organization with Code",
    academyJoinCode: "Have an Academy or School Join Code?",
    academyJoinHint:
      "Connect your student account with your educational center to unlock private curriculum and group schedules.",
    enterCode: "Enter Code",
    enrolledCourses: "Enrolled Courses",
    submittedSolutions: "Submitted Solutions",
    totalSpend: "Total Spend",
    myCourses: "My Courses",
    mySubmissionsGrades: "My Submissions & Grades",
    inProgressCourses: "In-Progress Courses",
    browseMoreCourses: "Browse More Courses",
    noActiveEnrollments: "No active enrollments yet",
    exploreCatalogHint:
      "Explore our course catalog and enroll in your first course.",
    continueClassroom: "Continue Classroom",
    assignmentSubmissionsFeedback: "Assignment Submissions & Feedback",
    gradedHomeworkHint: "View graded homework, scores, and teacher comments.",
    assignment: "Assignment",
    course: "Course",
    status: "Status",
    submittedDate: "Submitted Date",
    noAssignmentSolutions: "No assignment solutions submitted yet.",
    underReview: "Under Review",
    comments: "No comments yet",
    quizAttemptsScores: "Quiz Attempts & Test Scores",
    quizSummaryHint: "Summary of multiple choice and module quizzes completed.",
    quizTitle: "Quiz Title",
    result: "Result",
    completedDate: "Completed Date",
    noQuizAttempts: "No quiz attempts recorded yet.",
    needsReviewStatus: "Needs Review",
    pts: "Pts",
    enrollmentStatus: "Enrollment Status",
    pending: "Pending",
    active: "Active",
    completed: "Completed",
    dropped: "Dropped",
    cancelled: "Cancelled",
    updateStatus: "Update status",
    statusUpdated: "Status Updated",
    statusUpdateFailed: "Status Update Failed",
    statusUpdateError: "Could not update enrollment status",
    confirmEnrollment: "Confirm Course Enrollment",
    enrollmentDescription:
      "Instant access to all modules, quizzes, and certificate of completion.",
    lifetimePass: "Full Access Lifetime Pass",
    total: "Total",
    fullLessonAccess: "Full video & text lesson access",
    practicalReview: "Interactive quizzes & practical assignments",
    verifiedCredential: "Verified digital credential upon completion",
    confirmEnrollNow: "Confirm & Enroll Now",
    enrollmentSuccessful: "Enrollment Successful!",
    enrollmentSuccessMessage: "You are now enrolled in {course}.",
    enrollmentFailed: "Enrollment Failed",
    enrollmentError: "Could not complete enrollment",
    backToInstructorDashboard: "Back to Instructor Dashboard",
    courseDetails: "Course Details",
    manageCurriculum:
      "Manage curriculum modules, attach interactive quizzes, and inspect student roster & progress.",
    addLessonModule: "Add Lesson Module",
    studentView: "Student View",
    totalModules: "Total Modules",
    lessons: "Lessons",
    assessments: "Assessments",
    items: "Items",
    curriculumSyllabus: "Curriculum Syllabus",
    modules: "Modules",
    addLesson: "Add Lesson",
    noLessonsCreated: "No Lessons Created Yet",
    buildCurriculumHint:
      "Begin building this course curriculum by adding your first module, video, reading notes, and assessments.",
    createFirstLesson: "Create First Lesson Module",
    published: "Published",
    draft: "Draft",
    addQuiz: "Add Quiz",
    addAssignment: "Add Assignment",
    editLesson: "Edit Lesson",
    deleteLesson: "Delete Lesson",
    quizzes: "Quizzes",
    newQuiz: "New Quiz",
    mins: "Mins",
    noQuizzesAttached: "No quizzes attached.",
    assignments: "Assignments",
    newAssignment: "New Assignment",
    noAssignmentsAttached: "No assignments attached.",
    noDeadline: "No deadline",
    enrolledCourseRoster: "Enrolled Course Roster",
    students: "Students",
    trackStudentProgress:
      "Track student progress, monitor payment status, and manage participation.",
    filterStudent: "Filter student name/email...",
    noEnrolledStudents: "No Enrolled Students Found",
    noMatchingStudents: "No students matching your search.",
    noStudentsCourse: "No students are currently enrolled in this course.",
    payment: "Payment",
    enrolledDate: "Enrolled Date",
    actions: "Actions",
    updateProgress: "Update Progress",
    dueDate: "Due",
    editLessonModule: "Edit Lesson Module",
    addLessonModuleTitle: "Add Lesson Module",
    addCurriculumContent: "Add curriculum content for {course}.",
    lessonTitle: "Lesson Title",
    lessonTitlePlaceholder:
      "e.g. Introduction to Asynchronous Programming in JS",
    lessonContentNotes: "Lesson Content / Notes",
    lessonContentPlaceholder:
      "Comprehensive text notes, reading material, or lecture overview...",
    materialUrl: "Video / Stream / Material URL (Optional)",
    publishImmediately: "Publish immediately (Visible to enrolled students)",
    saveChanges: "Save Changes",
    createLesson: "Create Lesson",
    updateStudentProgress: "Update Student Progress",
    adjustCompletion: "Manually adjust student completion percentage.",
    progressPercentage: "Progress Percentage (0 - 100%)",
    saveProgress: "Save Progress",
  },
  ar: {
    signIn: "تسجيل الدخول",
    register: "إنشاء حساب",
    getStarted: "ابدأ الآن",
    signOut: "تسجيل الخروج",
    dashboard: "لوحة التحكم",
    courses: "الدورات",
    organizations: "المؤسسات",
    language: "English",
    lightMode: "التبديل إلى الوضع الفاتح",
    darkMode: "التبديل إلى الوضع الداكن",
    chooseOrganization: "اختر مؤسستك",
    organizationHint: "اختر المجتمع التعليمي الذي تنتمي إليه.",
    noOrganizations: "لا توجد مؤسسات نشطة متاحة حاليًا.",
    loadOrganizationsError: "تعذر تحميل المؤسسات. حاول مرة أخرى.",
    loadingOrganizations: "جار تحميل المؤسسات...",
    registrationTitle: "انضم إلى EduSphere اليوم",
    registrationSubtitle: "أنشئ ملفك الدراسي وابدأ رحلة التعلم",
    fullName: "الاسم الكامل",
    emailAddress: "البريد الإلكتروني",
    password: "كلمة المرور",
    personalPhone: "رقم الهاتف الشخصي",
    educationLevel: "المرحلة التعليمية",
    gender: "النوع",
    male: "ذكر",
    female: "أنثى",
    school: "المدرسة / الجامعة",
    address: "العنوان / المدينة",
    parentName: "اسم ولي الأمر",
    parentPhone: "رقم هاتف ولي الأمر",
    createStudentAccount: "إنشاء حساب طالب",
    alreadyRegistered: "لديك حساب بالفعل؟",
    signInHere: "سجل الدخول هنا",
    passwordHint:
      "يجب أن تتضمن حرفًا كبيرًا وصغيرًا ورقمًا ورمزًا (مثل Pass@123)",
    registrationSuccess: "تم التسجيل بنجاح!",
    verifyInstruction: "تحقق من بريدك الإلكتروني لتفعيل حسابك.",
    registrationFailed: "فشل التسجيل",
    registrationError: "تعذر إنشاء الحساب",
    loginSubtitle: "أدخل بياناتك للوصول إلى لوحة التحكم",
    rememberMe: "تذكرني",
    forgotPassword: "هل نسيت كلمة المرور؟",
    noAccount: "ليس لديك حساب؟",
    createAccount: "إنشاء حساب",
    primary: "المرحلة الابتدائية",
    preparatory: "المرحلة الإعدادية",
    secondary: "المرحلة الثانوية",
    university: "الجامعة",
    graduate: "الدراسات العليا",
    other: "أخرى",
    welcomeBack: "مرحبًا بعودتك!",
    signedInMessage: "تم تسجيل الدخول إلى حسابك بنجاح.",
    authenticationFailed: "فشل تسجيل الدخول",
    invalidCredentials: "بيانات الدخول غير صحيحة",
    verifyAlmostThere: "اقتربت من الانتهاء",
    verifyEmailTitle: "تأكيد بريدك الإلكتروني",
    verifyEmailMessage: "أرسلنا رابط التأكيد إلى",
    yourEmailAddress: "بريدك الإلكتروني",
    verifyEmailActivate: "تحقق من بريدك الوارد لتفعيل حسابك.",
    linkValidFor: "رابط التأكيد صالح لمدة",
    minutes: "دقائق",
    checkSpam: "إذا لم تجد الرسالة، تحقق من مجلد الرسائل غير المرغوب فيها.",
    openEmailProvider: "فتح مزود البريد الإلكتروني",
    openGmail: "فتح Gmail",
    openOutlook: "فتح Outlook",
    wrongEmail: "هل البريد الإلكتروني غير صحيح؟",
    registerAnotherEmail: "التسجيل ببريد إلكتروني آخر",
    noVerificationToken: "لم يتم العثور على رمز التأكيد في الرابط.",
    emailVerified: "تم تأكيد البريد الإلكتروني!",
    emailVerifiedMessage: "تم تأكيد بريدك الإلكتروني بنجاح.",
    verificationFailed:
      "فشل تأكيد البريد الإلكتروني. قد يكون الرابط غير صالح أو منتهي الصلاحية.",
    verifyingEmail: "جار تأكيد بريدك الإلكتروني",
    validatingLink: "انتظر قليلًا حتى نتحقق من رابط التفعيل...",
    accountActivated: "تم تفعيل الحساب",
    verifiedSuccessfully: "تم تأكيد البريد الإلكتروني بنجاح!",
    accountActiveMessage:
      "تم تأكيد بريدك الإلكتروني وأصبح حسابك الطلابي نشطًا بالكامل.",
    redirectingLogin: "سيتم تحويلك إلى تسجيل الدخول خلال",
    verificationFailedTitle: "فشل التأكيد",
    linksExpire:
      "تنتهي صلاحية روابط التأكيد بعد 15 دقيقة. إذا انتهت صلاحية الرابط، سجل الدخول أو أنشئ حسابًا جديدًا.",
    retry: "إعادة المحاولة",
    forgotTitle: "هل نسيت كلمة المرور؟",
    forgotSubtitle:
      "أدخل بريدك الإلكتروني وسنرسل لك رابطًا آمنًا لإعادة التعيين.",
    sendResetLink: "إرسال رابط التعيين",
    resetEmailSent: "تم إرسال رابط التعيين",
    resetEmailSentMessage:
      "إذا كان هناك حساب بهذا البريد، فستصلك تعليمات إعادة تعيين كلمة المرور قريبًا.",
    backToSignIn: "العودة إلى تسجيل الدخول",
    resetTitle: "إنشاء كلمة مرور جديدة",
    resetSubtitle: "اختر كلمة مرور قوية لحسابك في EduSphere.",
    newPassword: "كلمة المرور الجديدة",
    confirmPassword: "تأكيد كلمة المرور",
    resetPassword: "إعادة تعيين كلمة المرور",
    passwordMismatch: "كلمتا المرور غير متطابقتين.",
    missingResetToken: "رابط إعادة تعيين كلمة المرور لا يحتوي على الرمز.",
    resetSuccess: "تم تغيير كلمة المرور بنجاح",
    resetSuccessMessage: "تم تغيير كلمة المرور. يمكنك الآن تسجيل الدخول.",
    searchPlaceholder: "ابحث عن الدورات والمهارات والموضوعات...",
    closeMenu: "إغلاق القائمة",
    openMenu: "فتح القائمة",
    notifications: "الإشعارات",
    user: "المستخدم",
    myProfile: "ملفي الشخصي",
    menuNavigation: "قائمة التنقل",
    myOverview: "نظرة عامة",
    browseCatalog: "تصفح الدورات",
    accountProfile: "الملف الشخصي",
    teachingHub: "مركز التدريس",
    newCourse: "دورة جديدة",
    submissionsGrading: "التسليمات والتقييم",
    profile: "الملف الشخصي",
    executiveAnalytics: "التحليلات التنفيذية",
    usersRoles: "المستخدمون والأدوار",
    teacherRoster: "قائمة المدرسين",
    categories: "التصنيفات",
    financialLedger: "السجل المالي",
    eduSphereLms: "منصة EduSphere التعليمية",
    platformVersion: "منصة دورات جاهزة للإنتاج، الإصدار 1.0",
    myProfileDescription: "إدارة ملفك الشخصي وإعدادات حسابك.",
    exploreCourses: "استكشف الدورات",
    platformRoles: "المنصة والأدوار",
    connectSocial: "التواصل والشبكات الاجتماعية",
    webDevelopment: "تطوير الويب",
    dataScience: "علوم البيانات والذكاء الاصطناعي",
    businessFinance: "الأعمال والتمويل",
    designUx: "التصميم وتجربة المستخدم",
    instructorPortal: "بوابة المدرسين",
    studentEnrollment: "تسجيل الطلاب",
    adminDashboard: "لوحة تحكم الإدارة",
    allRightsReserved: "جميع الحقوق محفوظة.",
    builtForEducation: "صُممت للتعليم الرقمي من الجيل القادم.",
    privacyPolicy: "سياسة الخصوصية",
    termsService: "شروط الخدمة",
    security: "الأمان",
    portal: "البوابة",
    closeSidebar: "إغلاق الشريط الجانبي",
    platformDescription: "منصة تعليم إلكتروني متقدمة للتعلم الرقمي الحديث.",
    institutionalDirectory: "دليل المؤسسات",
    partnerOrganizations: "المؤسسات والمراكز الشريكة",
    exploreOrganizations:
      "استكشف الجامعات والأكاديميات ومراكز التدريب التي تستضيف دورات على EduSphere.",
    joinWithCode: "الانضمام برمز",
    organizationJoinCode: "هل لديك رمز انضمام لمؤسسة؟",
    joinCodeHint:
      "أدخل رمز الدعوة الخاص بالأكاديمية أو المدرسة لربط حسابك والوصول إلى الدروس الخاصة والجداول الدراسية.",
    enterJoinCode: "إدخال رمز الانضمام",
    noOrganizationsListed: "لا توجد مؤسسات شريكة نشطة حاليًا.",
    activeHub: "مركز نشط",
    verifiedPartner: "شريك موثق",
    knowledgeBase: "قاعدة المعرفة",
    courseCatalog: "دليل الدورات",
    discoverCourses:
      "اكتشف دورات معتمدة يقدمها مدربون موثقون في التقنية والأعمال والعلوم.",
    searchCourseTopic: "ابحث عن عنوان الدورة أو الموضوع...",
    allCourses: "كل الدورات",
    noCoursesMatch: "لا توجد دورات تطابق معاييرك",
    adjustSearch: "حاول تعديل البحث أو اختيار تصنيف مختلف.",
    general: "عام",
    instructor: "المدرب",
    progress: "التقدم",
    courseFee: "رسوم الدورة",
    free: "مجانًا",
    viewDetails: "عرض التفاصيل",
    courseTuition: "رسوم الدورة",
    lifetimeAccess: "وصول كامل مدى الحياة",
    quizAssignmentReview: "اختبارات ومراجعة واجبات البرمجة",
    completionCertificate: "شهادة إتمام الدورة",
    enrollCourse: "الالتحاق بالدورة",
    courseCurriculum: "منهج الدورة",
    publishingLessons: "يتم نشر دروس هذه الدورة حاليًا.",
    videoLecture: "محاضرة فيديو",
    readingModule: "وحدة قراءة",
    startLesson: "بدء الدرس",
    lesson: "الدرس",
    interactiveAssessment: "تقييم تفاعلي",
    questionOf: "السؤال {current} من {total}",
    loadingQuestions: "جار تحميل أسئلة التقييم...",
    noQuestions: "لا توجد أسئلة متاحة",
    noPublishedQuestions:
      "لا يحتوي هذا الاختبار على أسئلة منشورة بعد. حاول مرة أخرى لاحقًا.",
    typeResponse: "اكتب إجابتك هنا...",
    previous: "السابق",
    nextQuestion: "السؤال التالي",
    submitAssessment: "إرسال التقييم",
    assessmentPassed: "تم اجتياز التقييم!",
    quizSubmitted: "تم إرسال الاختبار",
    yourScore: "درجتك",
    points: "نقاط",
    submissionError: "خطأ في الإرسال",
    failedSubmitQuiz: "تعذر إرسال الاختبار. حاول مرة أخرى.",
    quizCompleted: "اكتمل الاختبار!",
    finalScore: "درجتك النهائية",
    passedAssessment: "تم اجتياز التقييم",
    needsReview: "يحتاج إلى مراجعة",
    tryAgain: "حاول مرة أخرى",
    worth: "الدرجة",
    assignmentInstructions: "تعليمات الواجب",
    totalPoints: "إجمالي النقاط",
    missingContent: "المحتوى مفقود",
    provideSubmission: "يرجى تقديم نص الإجابة أو رابط الملف.",
    assignmentSubmitted: "تم إرسال الواجب",
    submissionReceived: "تم استلام إجابتك من المدرب.",
    currentSubmissionStatus: "حالة الإرسال الحالية",
    grade: "الدرجة",
    instructorFeedback: "ملاحظات المدرب",
    yourAnswerNotes: "إجابتك / ملاحظاتك",
    writeSolution: "اكتب حل الواجب أو ملخصه أو إجابتك هنا...",
    projectLink: "رابط المستند / المشروع (اختياري)",
    cancel: "إلغاء",
    submitAssignment: "إرسال الواجب",
    externalLearningMaterial: "مواد ومصادر تعليمية خارجية",
    supplementaryMaterial:
      "يتضمن هذا الدرس مستندات إضافية أو مستودعات مشاريع أو أدلة دراسية تفاعلية.",
    openResource: "فتح رابط المصدر",
    interactiveReading: "وحدة قراءة تفاعلية",
    studyNotes: "ادرس الملاحظات أدناه وأكمل اختبارات وواجبات الوحدة.",
    lessonQuizzes: "اختبارات الدرس",
    noQuizzes: "لا توجد اختبارات مرتبطة بهذا الدرس.",
    questions: "أسئلة",
    pass: "النجاح",
    passed: "تم الاجتياز",
    failed: "لم ينجح",
    score: "النتيجة",
    retakeQuiz: "إعادة الاختبار",
    takeQuiz: "بدء الاختبار",
    lessonAssignments: "واجبات الدرس",
    noAssignments: "لا توجد واجبات مرتبطة بهذا الدرس.",
    graded: "تم التقييم",
    submittedPending: "تم الإرسال (بانتظار المراجعة)",
    notSubmitted: "لم يتم الإرسال",
    viewUpdateSubmission: "عرض / تحديث الإرسال",
    submitWork: "إرسال العمل",
    instructorFeedbackLabel: "ملاحظات المدرب",
    noLessonNotes: "لا توجد ملاحظات نصية لهذه الوحدة.",
    backToLessonNotes: "العودة إلى ملاحظات الدرس",
    courseAccessDenied: "تم رفض الوصول إلى الدورة",
    courseAccessDeniedHint:
      "تنتمي هذه الدورة إلى مدرب آخر أو لم تعد متاحة في مساحة التدريس الخاصة بك.",
    backToTeacherDashboard: "العودة إلى لوحة تحكم المدرب",
    studentProgressSummary:
      "تابع تقدمك في الدورات والمواد الدراسية والدرجات والشهادات الأكاديمية.",
    affiliation: "الانتماء",
    change: "تغيير",
    switchOrganizationTitle: "تغيير المؤسسة أو إدخال رمز مؤسسة جديدة",
    joinOrganizationCode: "الانضمام إلى مؤسسة برمز",
    academyJoinCode: "هل لديك رمز انضمام للأكاديمية أو المدرسة؟",
    academyJoinHint:
      "اربط حسابك الطلابي بمركزك التعليمي للوصول إلى المنهج الخاص والجداول الجماعية.",
    enterCode: "إدخال الرمز",
    enrolledCourses: "الدورات المسجل بها",
    submittedSolutions: "الحلول المرسلة",
    totalSpend: "إجمالي الإنفاق",
    myCourses: "دوراتي",
    mySubmissionsGrades: "إرسالياتي ودرجاتي",
    inProgressCourses: "الدورات قيد التقدم",
    browseMoreCourses: "تصفح المزيد من الدورات",
    noActiveEnrollments: "لا توجد تسجيلات نشطة بعد",
    exploreCatalogHint: "استكشف دليل الدورات وسجل في أول دورة لك.",
    continueClassroom: "متابعة قاعة التعلم",
    assignmentSubmissionsFeedback: "إرساليات الواجبات والملاحظات",
    gradedHomeworkHint: "اعرض الواجبات المصححة والدرجات وتعليقات المدربين.",
    assignment: "الواجب",
    course: "الدورة",
    status: "الحالة",
    submittedDate: "تاريخ الإرسال",
    noAssignmentSolutions: "لم يتم إرسال حلول واجبات بعد.",
    underReview: "قيد المراجعة",
    comments: "لا توجد تعليقات بعد",
    quizAttemptsScores: "محاولات الاختبارات والدرجات",
    quizSummaryHint:
      "ملخص الاختبارات متعددة الخيارات واختبارات الوحدات المكتملة.",
    quizTitle: "عنوان الاختبار",
    result: "النتيجة",
    completedDate: "تاريخ الإكمال",
    noQuizAttempts: "لم يتم تسجيل محاولات اختبارات بعد.",
    needsReviewStatus: "تحتاج إلى مراجعة",
    pts: "نقطة",
    enrollmentStatus: "حالة التسجيل",
    pending: "قيد الانتظار",
    active: "نشط",
    completed: "مكتمل",
    dropped: "منسحب",
    cancelled: "ملغى",
    updateStatus: "تحديث الحالة",
    statusUpdated: "تم تحديث الحالة",
    statusUpdateFailed: "فشل تحديث الحالة",
    statusUpdateError: "تعذر تحديث حالة التسجيل",
    confirmEnrollment: "تأكيد التسجيل في الدورة",
    enrollmentDescription:
      "وصول فوري إلى جميع الوحدات والاختبارات وشهادة إتمام الدورة.",
    lifetimePass: "وصول كامل مدى الحياة",
    total: "الإجمالي",
    fullLessonAccess: "وصول كامل إلى دروس الفيديو والنصوص",
    practicalReview: "اختبارات تفاعلية وواجبات عملية",
    verifiedCredential: "شهادة رقمية موثقة عند الإكمال",
    confirmEnrollNow: "تأكيد التسجيل الآن",
    enrollmentSuccessful: "تم التسجيل بنجاح!",
    enrollmentSuccessMessage: "تم تسجيلك الآن في {course}.",
    enrollmentFailed: "فشل التسجيل",
    enrollmentError: "تعذر إكمال التسجيل",
    backToInstructorDashboard: "العودة إلى لوحة تحكم المدرب",
    courseDetails: "تفاصيل الدورة",
    manageCurriculum:
      "إدارة وحدات المنهج وإضافة الاختبارات التفاعلية ومراجعة قائمة الطلاب وتقدمهم.",
    addLessonModule: "إضافة وحدة درس",
    studentView: "عرض الطالب",
    totalModules: "إجمالي الوحدات",
    lessons: "الدروس",
    assessments: "التقييمات",
    items: "عناصر",
    curriculumSyllabus: "خطة المنهج",
    modules: "الوحدات",
    addLesson: "إضافة درس",
    noLessonsCreated: "لم يتم إنشاء دروس بعد",
    buildCurriculumHint:
      "ابدأ ببناء منهج الدورة بإضافة أول وحدة وفيديو وملاحظات قراءة وتقييمات.",
    createFirstLesson: "إنشاء أول وحدة درس",
    published: "منشور",
    draft: "مسودة",
    addQuiz: "إضافة اختبار",
    addAssignment: "إضافة واجب",
    editLesson: "تعديل الدرس",
    deleteLesson: "حذف الدرس",
    quizzes: "الاختبارات",
    newQuiz: "اختبار جديد",
    mins: "دقائق",
    noQuizzesAttached: "لا توجد اختبارات مرفقة.",
    assignments: "الواجبات",
    newAssignment: "واجب جديد",
    noAssignmentsAttached: "لا توجد واجبات مرفقة.",
    noDeadline: "لا يوجد موعد نهائي",
    enrolledCourseRoster: "قائمة الطلاب المسجلين في الدورة",
    students: "الطلاب",
    trackStudentProgress: "تابع تقدم الطلاب وراقب حالة الدفع وأدر المشاركة.",
    filterStudent: "تصفية اسم الطالب أو بريده...",
    noEnrolledStudents: "لم يتم العثور على طلاب مسجلين",
    noMatchingStudents: "لا يوجد طلاب يطابقون بحثك.",
    noStudentsCourse: "لا يوجد طلاب مسجلون في هذه الدورة حاليًا.",
    payment: "الدفع",
    enrolledDate: "تاريخ التسجيل",
    actions: "الإجراءات",
    updateProgress: "تحديث التقدم",
    dueDate: "الاستحقاق",
    editLessonModule: "تعديل وحدة الدرس",
    addLessonModuleTitle: "إضافة وحدة درس",
    addCurriculumContent: "إضافة محتوى المنهج لـ {course}.",
    lessonTitle: "عنوان الدرس",
    lessonTitlePlaceholder: "مثال: مقدمة إلى البرمجة غير المتزامنة في JS",
    lessonContentNotes: "محتوى الدرس / الملاحظات",
    lessonContentPlaceholder:
      "ملاحظات نصية شاملة أو مواد قراءة أو ملخص المحاضرة...",
    materialUrl: "رابط الفيديو / البث / المادة (اختياري)",
    publishImmediately: "النشر فورًا (مرئي للطلاب المسجلين)",
    saveChanges: "حفظ التغييرات",
    createLesson: "إنشاء الدرس",
    updateStudentProgress: "تحديث تقدم الطالب",
    adjustCompletion: "تعديل نسبة إكمال الطالب يدويًا.",
    progressPercentage: "نسبة التقدم (0 - 100٪)",
    saveProgress: "حفظ التقدم",
  },
};

const PreferencesContext = createContext<AppPreferencesValue | null>(null);

const getStoredLocale = (): Locale => {
  if (typeof window === "undefined") return "en";
  const savedLocale = localStorage.getItem("locale");
  return savedLocale === "ar" ? "ar" : "en";
};

const getStoredTheme = (): Theme => {
  if (typeof window === "undefined") return "dark";
  const savedTheme = localStorage.getItem("theme");
  return savedTheme === "light" ? "light" : "dark";
};

export function AppPreferences({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const [locale, setLocale] = useState<Locale>(getStoredLocale);
  const [theme, setTheme] = useState<Theme>(getStoredTheme);

  useEffect(() => {
    localStorage.setItem("locale", locale);
    localStorage.setItem("theme", theme);
    document.documentElement.lang = locale;
    document.documentElement.dir = locale === "ar" ? "rtl" : "ltr";
    document.documentElement.dataset.theme = theme;
  }, [locale, theme]);

  const value = useMemo<AppPreferencesValue>(
    () => ({
      locale,
      theme,
      isArabic: locale === "ar",
      setLocale: (nextLocale) => setLocale(nextLocale),
      toggleLocale: () =>
        setLocale((current) => (current === "en" ? "ar" : "en")),
      toggleTheme: () =>
        setTheme((current) => (current === "dark" ? "light" : "dark")),
      t: (key) => translations[locale][key] || translations.en[key] || key,
    }),
    [locale, theme],
  );

  return (
    <PreferencesContext.Provider value={value}>
      {children}
    </PreferencesContext.Provider>
  );
}

export function useAppPreferences() {
  const context = useContext(PreferencesContext);
  if (!context)
    throw new Error("useAppPreferences must be used inside AppPreferences");
  return context;
}
